-- PostgreSQL パーティションテーブル定義
-- CHIPDATA: 親テーブル（パーティション化）
-- パーティションキー: LD_PICKUP_DATE (RANGE) + MACHINE_ID (LIST)
CREATE TABLE IF NOT EXISTS CHIPDATA (
	id					SERIAL,
	machine_id			INTEGER NOT NULL,
	type_name			VARCHAR,
	lot_name			VARCHAR NOT NULL,
	serial				INTEGER NOT NULL,
	wano				INTEGER,
	wax					INTEGER,
	way					INTEGER,
	ld_pickup_date		TIMESTAMP NOT NULL,
	ld_trayid			VARCHAR,
	ld_tray_arm			VARCHAR,
	ld_tray_pocket_x	INTEGER,
	ld_tray_pocket_y	INTEGER,
	ld_tray_align_x		INTEGER,
	ld_tray_align_y		INTEGER,
	ld_arm1_collet		INTEGER,
	ld_alarm			INTEGER,
	dc1_pre_align_x		INTEGER,
	dc1_pre_align_y		INTEGER,
	dc1_pre_align_t		INTEGER,
	dc1_arm1_collet		INTEGER,
	dc1_stage_serial	VARCHAR,
	dc1_stage_count		INTEGER,
	dc1_probe_serial	VARCHAR,
	dc1_probe_count		INTEGER,
	dc1_probe_x1		INTEGER,
	dc1_probe_y1		INTEGER,
	dc1_probe_x2		INTEGER,
	dc1_probe_y2		INTEGER,
	dc1_stage_z			INTEGER,
	dc1_pin_z			INTEGER,
	dc1_chip_align_x	INTEGER,
	dc1_chip_align_y	INTEGER,
	dc1_chip_align_t	INTEGER,
	dc1_test_bin		INTEGER,
	dc1_arm2_collet		INTEGER,
	dc1_alarm			INTEGER,
	ac1_arm1_collet		INTEGER,
	ac1_stage_serial	VARCHAR,
	ac1_stage_count		INTEGER,
	ac1_probe_serial	VARCHAR,
	ac1_probe_count		INTEGER,
	ac1_probe_x1		INTEGER,
	ac1_probe_y1		INTEGER,
	ac1_probe_x2		INTEGER,
	ac1_probe_y2		INTEGER,
	ac1_stage_z			INTEGER,
	ac1_pin_z			INTEGER,
	ac1_chip_align_x	INTEGER,
	ac1_chip_align_y	INTEGER,
	ac1_chip_align_t	INTEGER,
	ac1_test_bin		INTEGER,
	ac1_arm2_collet		INTEGER,
	ac1_alarm			INTEGER,
	ac2_arm1_collet		INTEGER,
	ac2_stage_serial	VARCHAR,
	ac2_stage_count		INTEGER,
	ac2_probe_serial	VARCHAR,
	ac2_probe_count		INTEGER,
	ac2_probe_x1		INTEGER,
	ac2_probe_y1		INTEGER,
	ac2_probe_x2		INTEGER,
	ac2_probe_y2		INTEGER,
	ac2_stage_z			INTEGER,
	ac2_pin_z			INTEGER,
	ac2_chip_align_x	INTEGER,
	ac2_chip_align_y	INTEGER,
	ac2_chip_align_t	INTEGER,
	ac2_test_bin		INTEGER,
	ac2_arm2_collet		INTEGER,
	ac2_alarm			INTEGER,
	dc2_arm1_collet		INTEGER,
	dc2_stage_serial	VARCHAR,
	dc2_stage_count		INTEGER,
	dc2_probe_serial	VARCHAR,
	dc2_probe_count		INTEGER,
	dc2_probe_x1		INTEGER,
	dc2_probe_y1		INTEGER,
	dc2_probe_x2		INTEGER,
	dc2_probe_y2		INTEGER,
	dc2_stage_z			INTEGER,
	dc2_pin_z			INTEGER,
	dc2_chip_align_x	INTEGER,
	dc2_chip_align_y	INTEGER,
	dc2_chip_align_t	INTEGER,
	dc2_test_bin		INTEGER,
	dc2_arm2_collet		INTEGER,
	dc2_alarm			INTEGER,
	ip_arm1_collet		INTEGER,
	ip_stage_count		INTEGER,
	ip_surf_bin			INTEGER,
	ip_arm2_collet		INTEGER,
	ip_back_bin			INTEGER,
	ip_alarm			INTEGER,
	uld_pre_align_x		INTEGER,
	uld_pre_align_y		INTEGER,
	uld_pre_align_t		INTEGER,
	uld_trayid			VARCHAR,
	uld_pocket_x		INTEGER,
	uld_pocket_y		INTEGER,
	uld_pocket_align_x	INTEGER,
	uld_pocket_align_y	INTEGER,
	uld_arm1_collet		INTEGER,
	uld_put_date		TIMESTAMP,
	uld_chip_align_x	INTEGER,
	uld_chip_align_y	INTEGER,
	uld_pf				VARCHAR,
	uld_alarm			INTEGER,
	PRIMARY KEY (lot_name, serial, ld_pickup_date, machine_id)
) PARTITION BY RANGE (ld_pickup_date);

-- インデックス作成
CREATE INDEX IF NOT EXISTS idx_chipdata_machine_id ON CHIPDATA (machine_id);
CREATE INDEX IF NOT EXISTS idx_chipdata_lot_name ON CHIPDATA (lot_name);
CREATE INDEX IF NOT EXISTS idx_chipdata_pickup_date ON CHIPDATA (ld_pickup_date);

-- 複合インデックス（lot_name + serial）でWHERE lot_name + ORDER BY serialを高速化
CREATE INDEX IF NOT EXISTS idx_chipdata_lot_serial ON CHIPDATA (lot_name, serial);

-- PostgreSQL パーティションテーブル定義
-- CHIPDATA: 親テーブル（パーティション化）
-- パーティションキー: LD_PICKUP_DATE (RANGE) + MACHINE_ID (LIST)
CREATE TABLE IF NOT EXISTS CHIPDATA2 (
	id					SERIAL,
	machine_id			INTEGER NOT NULL,
	type_name			VARCHAR,
	lot_name			VARCHAR NOT NULL,
	serial				INTEGER NOT NULL,
	wano				INTEGER,
	wax					INTEGER,
	way					INTEGER,
	ld_pickup_date		TIMESTAMP NOT NULL,
	ld_trayid			VARCHAR,
	ld_tray_arm			VARCHAR,
	ld_tray_pocket_x	INTEGER,
	ld_tray_pocket_y	INTEGER,
	ld_tray_align_x		INTEGER,
	ld_tray_align_y		INTEGER,
	ld_arm1_collet		INTEGER,
	ldunit_alarm		INTEGER,
	dc1_pre_align_x		INTEGER,
	dc1_pre_align_y		INTEGER,
	dc1_pre_align_t		INTEGER,
	dc1_arm1_collet		INTEGER,
	dc1_stage_serial	VARCHAR,
	dc1_stage_count		INTEGER,
	dc1_probe_serial	VARCHAR,
	dc1_probe_count		INTEGER,
	dc1_probe_align_x	INTEGER,
	dc1_probe_align_y	INTEGER,
	dc1_probe_align_t	INTEGER,
	dc1_stage_z			INTEGER,
	dc1_pin_z			INTEGER,
	dc1_chip_align_x	INTEGER,
	dc1_chip_align_y	INTEGER,
	dc1_chip_align_t	INTEGER,
	dc1_test_bin		INTEGER,
	dc1_arm2_collet		INTEGER,
	ac1_arm1_collet		INTEGER,
	ac1_stage_serial	VARCHAR,
	ac1_stage_count		INTEGER,
	ac1_probe_serial	VARCHAR,
	ac1_probe_count		INTEGER,
	ac1_probe_align_x	INTEGER,
	ac1_probe_align_y	INTEGER,
	ac1_probe_align_t	INTEGER,
	ac1_stage_z			INTEGER,
	ac1_pin_z			INTEGER,
	ac1_chip_align_x	INTEGER,
	ac1_chip_align_y	INTEGER,
	ac1_chip_align_t	INTEGER,
	ac1_test_bin		INTEGER,
	ac1_arm2_collet		INTEGER,
	testunit1_alarm		INTEGER,
	ac2_arm1_collet		INTEGER,
	ac2_stage_serial	VARCHAR,
	ac2_stage_count		INTEGER,
	ac2_probe_serial	VARCHAR,
	ac2_probe_count		INTEGER,
	ac2_probe_align_x	INTEGER,
	ac2_probe_align_y	INTEGER,
	ac2_probe_align_t	INTEGER,
	ac2_stage_z			INTEGER,
	ac2_pin_z			INTEGER,
	ac2_chip_align_x	INTEGER,
	ac2_chip_align_y	INTEGER,
	ac2_chip_align_t	INTEGER,
	ac2_test_bin		INTEGER,
	ac2_arm2_collet		INTEGER,
	dc2_arm1_collet		INTEGER,
	dc2_stage_serial	VARCHAR,
	dc2_stage_count		INTEGER,
	dc2_probe_serial	VARCHAR,
	dc2_probe_count		INTEGER,
	dc2_probe_align_x	INTEGER,
	dc2_probe_align_y	INTEGER,
	dc2_probe_align_t	INTEGER,
	dc2_stage_z			INTEGER,
	dc2_pin_z			INTEGER,
	dc2_chip_align_x	INTEGER,
	dc2_chip_align_y	INTEGER,
	dc2_chip_align_t	INTEGER,
	dc2_test_bin		INTEGER,
	dc2_arm2_collet		INTEGER,
	testunit2_alarm		INTEGER,
	ip_stage_count		INTEGER,
	ip_surf_bin			INTEGER,
	uld_pre_align_x		INTEGER,
	uld_pre_align_y		INTEGER,
	uld_pre_align_t		INTEGER,
	uld_arm1_collet		INTEGER,
	ip_back_bin			INTEGER,
	uld_trayid			VARCHAR,
	uld_pocket_x		INTEGER,
	uld_pocket_y		INTEGER,
	uld_pocket_align_x	INTEGER,
	uld_pocket_align_y	INTEGER,
	uld_put_date		TIMESTAMP,
	uld_chip_align_x	INTEGER,
	uld_chip_align_y	INTEGER,
	uld_pf				VARCHAR,
	uldunit_alarm		INTEGER,
	PRIMARY KEY (lot_name, serial, ld_pickup_date, machine_id)
) PARTITION BY RANGE (ld_pickup_date);

-- インデックス作成
CREATE INDEX IF NOT EXISTS idx_chipdata_machine_id ON CHIPDATA2 (machine_id);
CREATE INDEX IF NOT EXISTS idx_chipdata_lot_name ON CHIPDATA2 (lot_name);
CREATE INDEX IF NOT EXISTS idx_chipdata_pickup_date ON CHIPDATA2 (ld_pickup_date);

-- 複合インデックス（lot_name + serial）でWHERE lot_name + ORDER BY serialを高速化
CREATE INDEX IF NOT EXISTS idx_chipdata_lot_serial ON CHIPDATA2 (lot_name, serial);


-- LOT管理テーブル（メタデータ）
CREATE TABLE IF NOT EXISTS LOTDATE (
	lot_name	VARCHAR PRIMARY KEY,
	start_date	TIMESTAMP NOT NULL,
	end_date	TIMESTAMP NOT NULL,
	machine_id	INTEGER
);

-- インデックス作成
CREATE INDEX IF NOT EXISTS idx_lotdate_dates ON LOTDATE (start_date, end_date);

-- イベント管理テーブル
CREATE TABLE IF NOT EXISTS events (
    id          SERIAL PRIMARY KEY,
    machine_id  INTEGER,
    type_name   VARCHAR,
    lot_name    VARCHAR NOT NULL,
    date        TIMESTAMP NOT NULL,
    event_type  VARCHAR NOT NULL,
    alarm_unit  VARCHAR,
    alarm_code  INTEGER
);

CREATE INDEX idx_events_lot_name ON events (lot_name);

